apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust
  template:
    metadata:
      labels:
        app: locust
    spec:
      containers:
        - name: locust
          image: locustio/locust:2.32.0
          args:
            - "-f"
            - "/mnt/locust/locustfile.py"
            - "--host=http://nginx:80"
            - "--web-host=0.0.0.0"
            - "--web-port=8089"
            - "--step-users=10"
            - "--step-time=30s"
          ports:
            - containerPort: 8089
          volumeMounts:
            - name: locustfile
              mountPath: /mnt/locust/locustfile.py
              subPath: locustfile.py
      volumes:
        - name: locustfile
          configMap:
            name: locust-config
---
apiVersion: v1
kind: Service
metadata:
  name: locust
  namespace: ecommerce
spec:
  type: NodePort
  selector:
    app: locust
  ports:
    - port: 8089
      targetPort: 8089
      nodePort: 38089
