name: Terraform Plan

on:
  pull_request:
    paths:
      - terraform/**

jobs:
  plan:
    runs-on: ubuntu-latest

    env:
      TFE_TOKEN: ${{ secrets.TFE_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ">= 1.6"
          cli_config_credentials_token: ${{ secrets.TFE_TOKEN }}

      - name: Terraform init
        run: terraform -chdir=terraform init

      - name: Terraform validate
        run: terraform -chdir=terraform validate

      - name: Terraform plan
        run: terraform -chdir=terraform plan -no-color
