name: Terraform Plan

on:
  pull_request:
    paths:
      - 'terraform/**'

jobs:
  plan:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ">= 1.6"

      - name: Terraform init
        run: terraform -chdir=terraform init

      - name: Terraform validate
        run: terraform -chdir=terraform validate

      - name: Terraform refresh
        run: terraform -chdir=terraform apply -refresh-only -auto-approve \
          -var="backend_image_registry_prefix=mock/" \
          -var="frontend_image_registry_prefix=mock/" \
          -var="nginx_image_registry_prefix=mock/"

      - name: Terraform plan
        run: terraform -chdir=terraform plan -no-color \
          -var="backend_image_registry_prefix=mock/" \
          -var="frontend_image_registry_prefix=mock/" \
          -var="nginx_image_registry_prefix=mock/"